plugins {
    id 'com.android.application'
}

android {
    namespace 'dev.alastor.bedrockforge'
    compileSdk 35

    defaultConfig {
        applicationId 'dev.alastor.bedrockforge'
        minSdk 26
        targetSdk 28
        versionCode 28
        versionName '0.1.28-alpha'
    }

    buildTypes {
        debug {
            debuggable true
        }
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation 'dev.rikka.shizuku:api:13.1.5'
    implementation 'dev.rikka.shizuku:provider:13.1.5'
    implementation 'org.powernukkit.bedrock.leveldb:bedrock-leveldb:0.11.0-PN'
}
