package dev.packsmith.mt;

import java.util.UUID;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

final class ManifestUtil {
    private ManifestUtil() {}
    static String rp() { return manifest("PackSmith Resource Pack","resources",null,null); }
    static String bp() { return manifest("PackSmith Behavior Pack","data",null,null); }
    static String linkedBp() { return manifest("PackSmith Behavior Pack","data","PUT_RESOURCE_PACK_HEADER_UUID_HERE","1, 0, 0"); }
    static String manifest(String name,String type,String dep,String depVersion) {
        String h=EditorUtil.uuid(), m=EditorUtil.uuid();
        StringBuilder s=new StringBuilder();
        s.append("{\n  \\\"format_version\\\": 2,\n  \\\"header\\\": {\n")
         .append("    \\\"name\\\": \\\"").append(name).append("\\\",\n")
         .append("    \\\"description\\\": \\\"Generated by PackSmith\\\",\n")
         .append("    \\\"uuid\\\": \\\"").append(h).append("\\\",\n")
         .append("    \\\"version\\\": [1, 0, 0],\n")
         .append("    \\\"min_engine_version\\\": [1, 21, 0]\n  },\n")
         .append("  \\\"modules\\\": [\n    {\n      \\\"type\\\": \\\"").append(type).append("\\\",\n")
         .append("      \\\"uuid\\\": \\\"").append(m).append("\\\",\n      \\\"version\\\": [1, 0, 0]\n    }\n  ]");
        if(dep!=null) s.append(",\n  \\\"dependencies\\\": [\n    {\n      \\\"uuid\\\": \\\"").append(dep).append("\\\",\n      \\\"version\\\": [").append(depVersion).append("]\n    }\n  ]");
        return s.append("\n}\n").toString().replace("\\\"","\"");
    }
    static String refreshHeaderAndModules(String text) {
        Pattern p=Pattern.compile("(\\\"uuid\\\"\\s*:\\s*\\\")[0-9a-fA-F-]{36}(\\\")");
        Matcher m=p.matcher(text); StringBuffer out=new StringBuffer(); int count=0;
        while(m.find()){
            count++;
            int dep=text.indexOf("\"dependencies\"");
            if(dep>=0 && m.start()>dep){ m.appendReplacement(out,Matcher.quoteReplacement(m.group())); continue; }
            m.appendReplacement(out,Matcher.quoteReplacement(m.group(1)+UUID.randomUUID()+m.group(2)));
        }
        m.appendTail(out); return out.toString();
    }
    static String validate(String t) {
        StringBuilder e=new StringBuilder();
        if(!t.contains("\"format_version\"") || !t.matches("(?s).*\\\"format_version\\\"\\s*:\\s*2.*")) add(e,"format_version should be 2");
        if(!t.contains("\"header\"")) add(e,"header is missing");
        if(!t.contains("\"modules\"")) add(e,"modules is missing");
        Matcher m=Pattern.compile("[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-5][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}").matcher(t);
        int n=0; while(m.find()) n++; if(n<2) add(e,"expected at least header and module UUIDs");
        return e.length()==0?"Manifest sanity check passed":e.toString();
    }
    static void add(StringBuilder b,String s){if(b.length()>0)b.append("; ");b.append(s);}
}
